Platform-OS/pos-module-user

- README.md
- public/graphql/session/destroy.graphql
- public/graphql/user/verify_password.graphql
- public/views/partials/lib/commands/session/create.liquid
- public/views/partials/lib/commands/session/destroy.liquid
- public/views/partials/lib/commands/user/verify_password.liquid
- public/views/partials/lib/hooks/hook_admin_menu.liquid
- public/views/partials/lib/hooks/hook_permission.liquid
- public/views/partials/lib/queries/role_permissions/get_all.liquid
https://trello.com/c/DwAUaLvD/31-use-access-control-for-all-modules-authorization
https://trello.com/c/WOQVlmCN/82-sessions-handling-authentication
> Authentication and authorization

- README.md
- public/views/pages/sessions/create.liquid
- public/views/pages/sessions/destroy.liquid
- public/views/pages/users/register.liquid
- public/views/partials/lib/commands/session/create.liquid
- public/views/partials/lib/commands/user/verify_password.liquid
- public/views/partials/lib/hooks/hook_admin_menu.liquid
- public/views/partials/lib/queries/user/load.liquid
https://trello.com/c/bvC8u6ww/91-user-forms-first-organism
User forms module is related: https://github.com/Platform-OS/pos-module-user-forms/pull/1
> Register and session handlers

- public/views/pages/sessions/create.liquid
- public/views/pages/sessions/destroy.liquid
- public/views/pages/users/register.liquid
- public/views/partials/lib/hooks/hook_permission.liquid
- public/views/partials/lib/queries/role_permissions/get_all.liquid
Add permission for user registration. This will be used to limit the registration in the GP alpha site.
https://trello.com/c/Zhhz17B3/123-sign-up-landing-page
> Permission handling for registration

- public/graphql/user/verify_password.graphql
- public/views/pages/sessions/create.liquid
- public/views/partials/lib/commands/session/create.liquid
- public/views/partials/lib/commands/user/verify_password.liquid
- public/views/partials/lib/commands/user/verify_password/build.liquid
- public/views/partials/lib/commands/user/verify_password/check.liquid
Use build/check during password validation.
> Use build/check when validating the authentication

- CHANGELOG.md
- README.md
- changelog-template.hbs
Rendering dates into changelog.
> Update changelog template

- README.md
- public/views/partials/lib/queries/user/load.liquid
> Enable to modify the loaded user object

- public/views/partials/lib/queries/user/load.liquid
Build anonymous user object without searching for the user in the database.
> Handle anonymous user in user load

- README.md
- public/views/pages/sessions/create.liquid
> Change session create endpoint's slug

- public/views/partials/lib/queries/registration_fields/load.liquid
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Add a query to collect registration fields

- public/views/partials/admin_pages/list.liquid
Admin update to display user data table
Use standard heading component from component library
> Admin update

- public/views/partials/lib/queries/registration_fields/load.liquid
Fix typo
https://trello.com/c/KiPjaWpH
> form label update

- public/graphql/user_roles/update.graphql
- public/views/partials/lib/commands/user_roles/update.liquid
Update command & gql mutation for `modules/user/user_roles`
> User roles: update command & mutation

- public/views/partials/lib/queries/user/load.liquid
Set the `current` flag automatically when loading a user.
> Set 'current' flag automatically

- public/model_schemas/user_roles.yml
> add belongs_to to user_roles

- public/views/partials/lib/commands/user/create.liquid
- public/views/partials/lib/commands/user/update.liquid
Delegate errors and validation from hooks to the user create/update command result
--
> User create/update validation

- public/views/partials/lib/commands/user/create.liquid
- public/views/partials/lib/commands/user/update.liquid
Hook result validation for user create/update
--
> Hook result validation for create/update

- README.md
- public/graphql/user/load.graphql
- public/views/partials/lib/queries/role_permissions/get_all.liquid
- public/views/partials/lib/queries/user/get_all.liquid
- public/views/partials/lib/queries/user/load.liquid
- public/views/partials/lib/queries/user_roles/get.liquid
I'm also wondering do we need `user_roles` table at all? Why don't store roles directly in user property?
> Remove n+1 on user_roles

- public/views/partials/lib/commands/user/create.liquid
- public/views/partials/lib/commands/user/create/check.liquid
- public/views/partials/lib/helpers/merge_hook_result.liquid
All input required for user registration must be validated first, before proceeding with the action. Because in case of errors in the way, actions can't be rolled back (not in a ACID transaction).
https://trello.com/c/c084SIMW/430-missing-error-message-when-you-request-to-join-and-unsuccessful-requests-add-to-registered-users
> Validate input before user creation

- README.md
Document `user_create_validate` hook.
> Document the user_create_validate hook

- modules/user/public/views/partials/lib/commands/session/create/check.liquid
- modules/user/public/views/partials/lib/commands/user/create/check.liquid
- modules/user/public/views/partials/lib/commands/user/update/check.liquid
- modules/user/public/views/partials/lib/commands/user/verify_password/check.liquid
- modules/user/template-values.json
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix-validations-deprecation

- README.md
- app/config.yml
- app/views/pages/admin/index.liquid
- app/views/pages/index.liquid
- app/views/partials/admin/home/index.liquid
- modules/user/public/lib/commands/session/create.liquid
- modules/user/public/lib/commands/session/impersonation/create.liquid
- modules/user/public/lib/commands/session/impersonation/create/build.liquid
- modules/user/public/lib/commands/session/impersonation/create/check.liquid
- modules/user/public/lib/commands/session/impersonation/destroy.liquid
- modules/user/public/lib/commands/session/impersonation/destroy/check.liquid
- modules/user/public/lib/events/impersonation_ended.liquid
- modules/user/public/lib/events/impersonation_started.liquid
- modules/user/public/views/pages/sessions/impersonation/create.liquid
- modules/user/public/views/pages/sessions/impersonation/destroy.liquid
Add "Logging as" functionality
https://github.com/orgs/Platform-OS/projects/11/views/1?pane=issue&itemId=95494757&issue=Platform-OS%7Cpos-module-community%7C465
> Logging as functionality

- modules/user/public/lib/commands/session/destroy.liquid
> Sesson clear after log|_out

- .github/workflows/call-platformos-check.yaml
Add a gh workflow to run platformos-check on liquid files
> add a workflow for platformos-check

- .github/workflows/e2e_tests.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> run tests on private stack

- .github/workflows/e2e_tests.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> remove modules package before deploy
